<a href="https://colab.research.google.com/github/OmarPorf/Apuntes-programacion/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#`NumPy`

Para hacer `arrays` en Python usamos el módulo `Numpy`



In [1]:
import numpy as np

#   Array de enteros

a = np.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


Algo importante que recalcar es que los arrays de `Numpy` son de ***elementos del mismo tipo***.

Si se quiere dar explícitamente el tipo de dato de los elementos, usamos el párametro `dtype`.

In [2]:
a = np.array([1, 2, 3, 4], dtype="float32")

print(a)

[1. 2. 3. 4.]


Además, los arrays también pueden ser multidimensionales.

In [4]:
a = np.array([range(_, _ + 5) for _ in range(5)])

print(a)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]




---


# Built-in arrays

`Numpy` tiene arrays ya integrados que nos ayudan a generar arrays más eficaz y eficientemente.


*   ***Array de solo ceros***

Para hacer un array de solo ceros se usa el método `zeros`.

In [6]:
#   Arreglo de 10 ceros de tipo int
a = np.zeros(10, dtype=int)

print(a)

[0 0 0 0 0 0 0 0 0 0]


*   ***Array de solo unos***

Para hacer un array de solo unos se usa el método `ones`.

In [10]:
#   Arreglo de 6 unos de tipo float
a = np.ones(6, dtype=float)

print(a)

[1. 1. 1. 1. 1. 1.]


Para hacer arrays multidimensionales, en vez de pasar un entero, se pasa una tupla `(n, m)`, donde `n` es el número de filas y `m` el número de columnas.

In [12]:
#   Matriz 3x4 de ceros de tipo float
a = np.zeros((3, 4), dtype=float)

print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


*   ***Rellenar un array***

Para rellenar un array de un solo elemento usamos el método `full`.

In [14]:
#   Matriz 2x4 de pi
a = np.full((2, 4), 3.141592)

print(a)

[[3.141592 3.141592 3.141592 3.141592]
 [3.141592 3.141592 3.141592 3.141592]]


*   ***Array de una secuencia lineal***

Para hacer lo equivalente a esto

```
lista = list(range(a, b, c))
```
usamos el método `arange`.


In [15]:
#   Arreglo de números pares del 2 al 20
a = np.arange(2, 21, 2)

print(a)

[ 2  4  6  8 10 12 14 16 18 20]


*   ***Array de elementos uniformemente espaciados***

Para hacer lo equivalente a esto

```
# intervalo [ini, fin] y n el número de divisiones del intervalo
esp = lambda x: x * (fin - ini) / n + ini
lista = [esp(i) for i in range(n + 1)]

```
se usa el método `linspace`.

In [16]:
#   Arreglo de las particiones del intervalo [3, 5] dividido en 10 partes
a = np.linspace(3, 5, 10)

print(a)

[3.         3.22222222 3.44444444 3.66666667 3.88888889 4.11111111
 4.33333333 4.55555556 4.77777778 5.        ]


*   ***Arreglo de números aleatorios uniformemente distribuidos***

Para hacer un arreglo de números aleatorios uniformemente distribuidos $\operatorname{U}(0, 1)$ usamos el método `random.random`.

In [17]:
#   Matriz 2x4 de números aleatorios entre 0 y 1
a = np.random.random((2, 4))

print(a)

[[0.08863705 0.88837117 0.38311975 0.87426352]
 [0.2284403  0.37018738 0.37437495 0.16155555]]


*   ***Arreglo de números aleatorios normalmente distribuidos***

Para hacer un arreglo de números aleatorios normalmente distribuidos $\operatorname{N}(\mu, \sigma)$ se usa el método `random.normal`.

In [18]:
#   Matriz 3x3 de números aleatorios normalmente distribuidos
#   con media 0 y desviación estándar 1
a = np.random.normal(0, 1, (3, 3))

print(a)

[[-1.21245016 -1.53502252 -0.04435596]
 [-0.15636962 -1.40840114  0.26758218]
 [ 0.05230651  0.04983219 -0.44558173]]


*   ***Arreglo de números aleatorios enteros uniformemente distribuidos***

Para hacer una arreglo de números aleatorios enteros uniformemente distribuidos $\operatorname{U}(a, b)$ se usa el método `random.randint`.

In [30]:
#   Matriz 4x1 de enteros aleatorios entre el 4 y el 20
a = np.random.randint(4, 20, (4, 2))

print(a)

[[10 16]
 [12  5]
 [ 4 18]
 [15  8]]


*   ***Matriz identidad***

Para hacer la matriz identidad $I_{n}$ se usa el método `eye`.

In [24]:
#   Matriz identidad 3x3 de tipo entero
a = np.eye(4, dtype=int)

print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


*   ***Arreglo no inicializado***

Para hacer un arreglo sin darle valores explícitos y solo su tamaño usamos el método `empty`.

In [27]:
#   Matriz 2x3 no inicializado (usa los valores que están en la memoria)
a = np.empty((2, 3), dtype=int)

print(a)

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]




---



---


# Tipos de datos admitidos
Los métodos de `NumPy` usan el parámetro `dtype`. Para especificar el tipo lo podemos hacer con string

```
np.empty(1, dtype='float16')
```
o con objeto `NumPy`

```
np.empty(1, dtype=np.float16)
```

| Tipo de dato | Descripción                      |
|--------------|----------------------------------|
| `bool`        | Booleano                         |
| `int`         | Entero                           |
| intc         | Entero en C                      |
| intp         | Entero para índices              |
| int8         | Entero de 8 bits                 |
| int16        | Entero de 16 bits                |
| int32        | Entero de 32 bits                |
| int64        | Entero de 64 bits                |
| uint8        | Entero sin signo de 8 bits       |
| uint16       | Entero sin signo de 16 bits      |
| uint32       | Entero sin signo de 32 bits      |
| uint64       | Entero sin signo de 64 bits      |
| `float`       | Float                            |
| float16      | Float de 16 bits                 |
| float32      | Float de 32 bits                 |
| float64      | Float de 64 bits                 |
| `complex`     | Complejo                         |
| complex64    | Complejo de 32($\Re$) + 32($\Im$) bits |
| complex128   | Complejo de 64($\Re$) + 64($\Im$) bits |